### ISSUE TITLE
Sign Up page Unit tests

### ISSUE THREAD

**Issue by MikelAlc** [MikelAlc/goofy-goobers-news-app#12]
2 or 3 should be fine

**Comment by tdraper** [comment]
working on it now

**Comment by tdraper** [comment]
tests applied:

1. renders successfully
2. Makes sure it is a signup form by testing fields for username, password, and confirm password
3. tests to make sure sign up button does not submit form when fields are empty

![image](https://github.com/MikelAlc/goofy-goobers-news-app/assets/107201220/592ccc3d-3bf7-40e1-a1bf-2aad41867472)
