### ISSUE TITLE
Sign In Page Unit Tests

### ISSUE THREAD

**Issue by MikelAlc** [MikelAlc/goofy-goobers-news-app#13]
2 or 3 should be fine

**Comment by tdraper** [comment]
tests applied:
1. renders successfully
2. Makes sure it is a signup form by testing fields for username, password, and confirm password
3. tests to make sure sign up button does not submit form when fields are empty

**Comment by tdraper** [comment]
closed the wrong issue

**Comment by tdraper** [comment]
Now issue is fixed:
1. login page renders successfully
2. has a login form
3. does not submit login form if fields are empty

![image](https://github.com/MikelAlc/goofy-goobers-news-app/assets/107201220/9e430f70-dc12-4c04-ad9a-97cb85599a77)
