### ISSUE TITLE
Search Tool

### ISSUE THREAD

**Issue by MikelAlc** [MikelAlc/goofy-goobers-news-app#28]
Requirement 6
– The landing page shall have a text box for entering search terms
• Requirement 7
– The search box will support use of AND, OR, and NOT
– The search box will support use of parenthesis
• Requirement 8
– The search results will display in descending order starting with the most
recent
• Requirement 9
– A meaningful message is displayed when there are no results to show

**Comment by tdraper** [comment]
cannot render search without even parenthesis

![image](https://github.com/MikelAlc/goofy-goobers-news-app/assets/107201220/a846ff85-7624-481b-a913-f0440987493a)

**Comment by tdraper** [comment]
Search is functional

https://media.discordapp.net/attachments/1113808682594091080/1123925171464577026/image.png?width=864&height=468

**Comment by tdraper** [comment]
tests past

![image](https://github.com/MikelAlc/goofy-goobers-news-app/assets/107201220/62010ca5-1316-4f82-b2a3-1cb6b94a0122)
